## Exploratory Data Analysis + Cleaning

In [7]:
import pandas as pd
import numpy as np


df = pd.read_csv("crop_insurance_deals_2023_Problem2.csv")
df.head()

,CROP_YEAR,STATE_CODE,STATE_ABBR,COUNTY_CODE,COUNTY_NAME,CROP_CODE,CROP_NAME,INSURANCE_PLAN_CODE,INSURANCE_PLAN_NAME,STAGE_CODE,...,NET_REPORTED_QUANTITY,COMPANION_QUANTITY,LIABILITY,TOTAL_PREMIUM,PRODUCER_PREMIUM,SUBSIDY,STATE_SUBSIDY,ADDITIONAL_SUBSIDY,INDEMNITY,LOSS_RATIO
0,2023,18,IN,63,hendricks,81,Soybeans,4,AYP,A,...,528.0,0,357127.0,10392.0,5300,0,0,0,0,0.00
1,2023,31,NE,39,Cuming,41,Corn,2,RP,A,...,20767.0,0,18876035.0,1285088.0,802858,0,0,0,3905137,3.04
2,2023,48,TX,123,De Witt,11,wheat,2,RP,A,...,17.0,0,2697.0,616.0,363,0,0,0,-,0.00
3,2023,38,ND,59,Morton,11,Wheat,2,RP,A,...,97662.0,0,29098195.0,5956764.0,4416194,0,0,0,1002769,0.17
4,2023,39,OH,107,Mercer,81,Soybeans,88,ECO-RP,A,...,0.0,164,5806.0,2084.0,917,0,0,0,0,0.00

In [8]:
print("Rows, Cols:", df.shape)
df.columns

Rows, Cols: (623, 28)

Index(['CROP_YEAR', 'STATE_CODE', 'STATE_ABBR', 'COUNTY_CODE', 'COUNTY_NAME',
       'CROP_CODE', 'CROP_NAME', 'INSURANCE_PLAN_CODE', 'INSURANCE_PLAN_NAME',
       'STAGE_CODE', 'COVERAGE_TYPE', 'COVERAGE_LEVEL', 'POLICIES_SOLD',
       'POLICIES_EARNING_PREMIUM', 'POLICIES_INDEMNIFIED',
       'UNITS_EARNING_PREMIUM', 'UNITS_INDEMNIFIED', 'QUANTITY_TYPE',
       'NET_REPORTED_QUANTITY', 'COMPANION_QUANTITY', 'LIABILITY',
       'TOTAL_PREMIUM', 'PRODUCER_PREMIUM', 'SUBSIDY', 'STATE_SUBSIDY',
       'ADDITIONAL_SUBSIDY', 'INDEMNITY', 'LOSS_RATIO'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 623 entries, 0 to 622
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CROP_YEAR                 623 non-null    int64
 1   STATE_CODE                623 non-null    int64
 2   STATE_ABBR                623 non-null    object
 3   COUNTY_CODE               623 non-null    int64
 4   COUNTY_NAME               613 non-null    object
 5   CROP_CODE                 623 non-null    int64
 6   CROP_NAME                 615 non-null    object
 7   INSURANCE_PLAN_CODE       623 non-null    int64
 8   INSURANCE_PLAN_NAME       623 non-null    object
 9   STAGE_CODE                623 non-null    object
 10  COVERAGE_TYPE             623 non-null    object
 11  COVERAGE_LEVEL            618 non-null    float64
 12  POLICIES_SOLD             623 non-null    int64
 13  POLICIES_EARNING_PREMIUM  623 non-null    int64
 14  POLICIES_INDEMNIFIED      623 non-null    int64
 15  UNITS_EARNING_PREMIUM     623 non-null    int64
 16  UNITS_INDEMNIFIED         623 non-null    int64
 17  QUANTITY_TYPE             623 non-null    object
 18  NET_REPORTED_QUANTITY     619 non-null    float64
 19  COMPANION_QUANTITY        623 non-null    int64
 20  LIABILITY                 612 non-null    float64
 21  TOTAL_PREMIUM             613 non-null    float64
 22  PRODUCER_PREMIUM          623 non-null    int64
 23  SUBSIDY                   623 non-null    int64
 24  STATE_SUBSIDY             623 non-null    int64
 25  ADDITIONAL_SUBSIDY        623 non-null    int64
 26  INDEMNITY                 623 non-null    object
 27  LOSS_RATIO                623 non-null    float64
dtypes: float64(5), int64(15), object(8)
memory usage: 136.4+ KB

In [10]:
missing = df.isna().sum().sort_values(ascending=False)
missing[missing > 0]

LIABILITY                11
COUNTY_NAME              10
TOTAL_PREMIUM            10
CROP_NAME                 8
COVERAGE_LEVEL            5
NET_REPORTED_QUANTITY     4
dtype: int64

In [12]:
df.describe(include="all")

,CROP_YEAR,STATE_CODE,STATE_ABBR,COUNTY_CODE,COUNTY_NAME,CROP_CODE,CROP_NAME,INSURANCE_PLAN_CODE,INSURANCE_PLAN_NAME,STAGE_CODE,...,NET_REPORTED_QUANTITY,COMPANION_QUANTITY,LIABILITY,TOTAL_PREMIUM,PRODUCER_PREMIUM,SUBSIDY,STATE_SUBSIDY,ADDITIONAL_SUBSIDY,INDEMNITY,LOSS_RATIO
count,623.000000,623.000000,623,623.000000,613,623.000000,615,623.000000,623,623,...,619.000000,623.000000,6.120000e+02,6.130000e+02,6.230000e+02,623.000000,623.0,623.0,623,623.000000
unique,NaN,NaN,31,NaN,358,NaN,18,NaN,14,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,306,NaN
top,NaN,NaN,NE,NaN,Lyon,NaN,Corn,NaN,RP,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
freq,NaN,NaN,77,NaN,7,NaN,230,NaN,266,609,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,298,NaN
mean,2023.000000,29.943820,NaN,111.004815,NaN,46.971108,NaN,13.064205,NaN,NaN,...,5668.562197,770.356340,4.222612e+06,6.558476e+07,2.084517e+05,101.898876,0.0,0.0,NaN,7.212103
std,0.126796,13.124376,NaN,88.949505,NaN,26.861185,NaN,23.033997,NaN,NaN,...,15921.556205,3484.758993,1.263539e+07,8.057837e+08,5.717441e+05,966.124301,0.0,0.0,NaN,79.884796
min,2022.000000,17.000000,NaN,1.000000,NaN,11.000000,NaN,1.000000,NaN,NaN,...,0.000000,0.000000,-5.000000e+05,0.000000e+00,0.000000e+00,0.000000,0.0,0.0,NaN,0.000000
25%,2023.000000,19.000000,NaN,47.000000,NaN,21.000000,NaN,2.000000,NaN,NaN,...,0.000000,0.000000,7.070750e+03,7.150000e+02,4.575000e+02,0.000000,0.0,0.0,NaN,0.000000
50%,2023.000000,27.000000,NaN,97.000000,NaN,41.000000,NaN,2.000000,NaN,NaN,...,96.000000,0.000000,1.225180e+05,1.270100e+04,7.986000e+03,0.000000,0.0,0.0,NaN,0.020000
75%,2023.000000,39.000000,NaN,147.000000,NaN,81.000000,NaN,17.000000,NaN,NaN,...,1404.000000,0.000000,1.164047e+06,1.528900e+05,8.717450e+04,0.000000,0.0,0.0,NaN,1.110000
max,2024.000000,99.000000,NaN,493.000000,NaN,81.000000,NaN,89.000000,NaN,NaN,...,143605.000000,43116.000000,1.034472e+08,1.000000e+10,4.416194e+06,15666.000000,0.0,0.0,NaN,999.990000

### Standardize Column Names

In [13]:
df.columns = [c.strip().upper() for c in df.columns]
df.columns

Index(['CROP_YEAR', 'STATE_CODE', 'STATE_ABBR', 'COUNTY_CODE', 'COUNTY_NAME',
       'CROP_CODE', 'CROP_NAME', 'INSURANCE_PLAN_CODE', 'INSURANCE_PLAN_NAME',
       'STAGE_CODE', 'COVERAGE_TYPE', 'COVERAGE_LEVEL', 'POLICIES_SOLD',
       'POLICIES_EARNING_PREMIUM', 'POLICIES_INDEMNIFIED',
       'UNITS_EARNING_PREMIUM', 'UNITS_INDEMNIFIED', 'QUANTITY_TYPE',
       'NET_REPORTED_QUANTITY', 'COMPANION_QUANTITY', 'LIABILITY',
       'TOTAL_PREMIUM', 'PRODUCER_PREMIUM', 'SUBSIDY', 'STATE_SUBSIDY',
       'ADDITIONAL_SUBSIDY', 'INDEMNITY', 'LOSS_RATIO'],
      dtype='object')

### Drop Duplicates

In [14]:
dup = df.duplicated().sum()
print("Duplicate full rows:", dup)

if dup > 0:
    df = df.drop_duplicates()
    print("After dropping duplicates:", df.shape)

Duplicate full rows: 11
After dropping duplicates: (612, 28)

### Convert Numeric columns

In [15]:
import numpy as np

expected_numeric = [
    "CROP_YEAR",
    "STATE_CODE", "COUNTY_CODE", "CROP_CODE",
    "COVERAGE_LEVEL",
    "POLICIES_SOLD", "POLICIES_INDEMNIFIED",
    "LIABILITY", "TOTAL_PREMIUM", "INDEMNITY",
    "LOSS_RATIO"
]
numeric_cols = [c for c in expected_numeric if c in df.columns]
print("Numeric cols found:", numeric_cols)

Numeric cols found: ['CROP_YEAR', 'STATE_CODE', 'COUNTY_CODE', 'CROP_CODE', 'COVERAGE_LEVEL', 'POLICIES_SOLD', 'POLICIES_INDEMNIFIED', 'LIABILITY', 'TOTAL_PREMIUM', 'INDEMNITY', 'LOSS_RATIO']

In [16]:
for col in numeric_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.replace("$", "", regex=False)
        .str.strip()
        .replace({"": np.nan, "nan": np.nan, "None": np.nan})
    )
    df[col] = pd.to_numeric(df[col], errors="coerce")

df[numeric_cols].dtypes

CROP_YEAR                 int64
STATE_CODE                int64
COUNTY_CODE               int64
CROP_CODE                 int64
COVERAGE_LEVEL          float64
POLICIES_SOLD             int64
POLICIES_INDEMNIFIED      int64
LIABILITY               float64
TOTAL_PREMIUM           float64
INDEMNITY               float64
LOSS_RATIO              float64
dtype: object

### Policies indemnified cannot exceed policies sold

In [17]:
if "POLICIES_SOLD" in df.columns and "POLICIES_INDEMNIFIED" in df.columns:
    bad = (df["POLICIES_INDEMNIFIED"] > df["POLICIES_SOLD"]).sum()
    print("Rows where indemnified > sold:", bad)

    df = df[df["POLICIES_INDEMNIFIED"] <= df["POLICIES_SOLD"]]
    print("After removing invalid policy rows:", df.shape)

Rows where indemnified > sold: 0
After removing invalid policy rows: (612, 28)

### No Negative Dollars

In [18]:
money_cols = [c for c in ["LIABILITY", "TOTAL_PREMIUM", "INDEMNITY"] if c in df.columns]

for c in money_cols:
    print(c, "negative rows:", (df[c] < 0).sum())

for c in money_cols:
    df = df[df[c] >= 0]

print("After removing negative financial rows:", df.shape)

LIABILITY negative rows: 4
TOTAL_PREMIUM negative rows: 0
INDEMNITY negative rows: 0
After removing negative financial rows: (582, 28)

### Recompute Loss Ratio

In [19]:
if "INDEMNITY" in df.columns and "TOTAL_PREMIUM" in df.columns:
    df["LOSS_RATIO_CALC"] = np.where(
        df["TOTAL_PREMIUM"] > 0,
        df["INDEMNITY"] / df["TOTAL_PREMIUM"],
        np.nan
    )

    if "LOSS_RATIO" in df.columns:
        diff = (df["LOSS_RATIO"] - df["LOSS_RATIO_CALC"]).abs()
        print("Loss ratio difference summary (raw vs calc):")
        print(diff.describe())

    df["LOSS_RATIO"] = df["LOSS_RATIO_CALC"]
    df.drop(columns=["LOSS_RATIO_CALC"], inplace=True)

Loss ratio difference summary (raw vs calc):
count    476.000000
mean       8.405208
std       91.313230
min        0.000000
25%        0.000000
50%        0.000834
75%        0.002974
max      999.990000
dtype: float64

### Any Missing Critical Fields?

In [20]:
critical = [c for c in ["STATE_ABBR", "CROP_NAME", "POLICIES_SOLD", "POLICIES_INDEMNIFIED", "LIABILITY", "TOTAL_PREMIUM", "INDEMNITY"] if c in df.columns]
df[critical].isna().sum().sort_values(ascending=False)

CROP_NAME               7
STATE_ABBR              0
POLICIES_SOLD           0
POLICIES_INDEMNIFIED    0
LIABILITY               0
TOTAL_PREMIUM           0
INDEMNITY               0
dtype: int64

### Drop Rows missing financial info

In [21]:
df = df.dropna(subset=[c for c in ["LIABILITY", "TOTAL_PREMIUM", "INDEMNITY"] if c in df.columns])
print("After dropping rows missing money fields:", df.shape)

After dropping rows missing money fields: (582, 28)

Saved: crop_insurance_deals_2023_Problem2_CLEAN.csv
Final rows: 582

In [23]:
print("Final row count:", len(df))

money_cols = [c for c in ["LIABILITY", "TOTAL_PREMIUM", "INDEMNITY"] if c in df.columns]
print("\nMissing in key money fields:")
print(df[money_cols].isna().sum())

print("\nLoss ratio range:")
if "LOSS_RATIO" in df.columns:
    print(df["LOSS_RATIO"].describe())

Final row count: 582

Missing in key money fields:
LIABILITY        0
TOTAL_PREMIUM    0
INDEMNITY        0
dtype: int64

Loss ratio range:
count    476.000000
mean       0.952492
std        1.623593
min        0.000000
25%        0.000000
50%        0.194410
75%        1.422450
max       11.793080
Name: LOSS_RATIO, dtype: float64

### Cleaning white space/naming conventions

In [24]:
text_cols = ["STATE_ABBR", "COUNTY_NAME", "CROP_NAME"]

for col in text_cols:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip()

In [25]:
text_cols = ["STATE_ABBR", "COUNTY_NAME", "CROP_NAME"]

for col in text_cols:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip()

In [27]:
# Clean crop names thoroughly
df["CROP_NAME"] = (
    df["CROP_NAME"]
    .astype(str)
    .str.strip()                 
    .str.replace(r"\s+", " ", regex=True)  
    .str.lower()                 
    .str.title()                 
)

df["CROP_NAME"].value_counts()

CROP_NAME
Corn         224
Soybeans     196
Wheat        125
Cotton        26
Nan            7
Maize          2
Soy Beans      2
Name: count, dtype: int64

In [28]:
df["CROP_NAME"].unique()

array(['Soybeans', 'Corn', 'Wheat', 'Cotton', 'Nan', 'Maize', 'Soy Beans'],
      dtype=object)

In [32]:
df.to_csv("crop_insurance_deals_2023_Problem2_CLEAN.csv", index=False)